import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      className = "bg-gradient-to-r from-rose-100 to-teal-100 z-20"
      >
        {children}
      </body>
    </html>
  );
}
